connection:
  ip: 192.168.0.0
  rack: 0
  slot: 2
app:
  periodicLogInterval: "24h"
  onChangeClock: "30s"
  enableWebServer: true
  enableOnChangeLog: true 
dataToLog:
    - name: "tag1"
      dbnumber: 0
      start: 0
      bit: 0
      type: "int"
      periodicLog: true
      onChangeLog: true
      showDashboard: true
    - name: "tag2"
      dbnumber: 2
      start: 0
      bit: 0
      type: "real"
      periodicLog: false
      onChangeLog: true
      showDashboard: true
    - name: "tag3"
      dbnumber: 3
      start: 2
      bit: 0
      type: "string"
      periodicLog: true
      onChangeLog: true
      showDashboard: true
    - name: "tag4"
      dbnumber: 4
      start: 0
      bit: 0
      type: "bool"
      periodicLog: true
      onChangeLog: true
      showDashboard: true
    - name: "tag5"
      dbnumber: 5
      start: 0
      bit: 0
      type: "bool"
      periodicLog: true
      onChangeLog: true
      showDashboard: true
      

