connection:
  ip: 192.168.2.2
  rack: "0"
  slot: "2"
  protocol: s7
  timeout: 200ms
  connectionRetry: 3
app:
  periodicLogInterval: "24h"
  onChangeClock: "30s"
  enableWebServer: true
  enableOnChangeLog: true 
dataToLog:
  - name: Tag1
    type: bool
    s7:
      dbNumber: 0
      offset: 0
      bit: 0
    opca:
      node: ""
    periodicLog: false
    onChangeLog: false
    showDashboard: false