connection:
  ip: 192.168.2.2
  rack: 0
  slot: 2
  protocol: s7
  timeout: 3s
  connectionRetry: 3
app:
  periodicLogInterval: 24h
  onChangeClock: 30s
  enableWebServer: true
  enableOnChangeLog: true 
  periodicLog:
    maxSize: 5242880 #5MB
    maxAge: 0
    archivePath: "./log/archive/periodic"
    archiveMaxSize: 104857600 #100MB
  onChangeLog:
    maxSize: 5242880 #5MB
    maxAge: 0
    archivePath: "./log/archive/onChange"
    archiveMaxSize: 104857600 #100MB
dataToLog:
  - name: Tag1
    type: bool
    s7:
      dbNumber: 0
      offset: 0
      bit: 0
    opca:
      node: ""
    periodicLog: false
    onChangeLog: false
    showDashboard: false