connection:
    ip: 192.168.2.2
    rack: "0"
    slot: "2"
app:
    periodicLogInterval: 30s
    onChangeClock: 0s
    enableWebServer: true
    enableOnChangeLog: true
dataToLog:
    - name: Tag1
      address: db0.dbx0.0
      type: bool
      periodicLog: false
      onChangeLog: false
      showDashboard: false
